---

- name: Playbook to provision most of the MoodleBox
  hosts: all
  vars:
    ansible_user: 'root'
  become: true

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Print out begin of build date and time
      ansible.builtin.debug:
        msg: 'Beginning of build: {{ lookup("pipe", "date +%Y-%m-%dT%H:%M:%S%z") }}'

    - name: Set fact with build start timestamp
      ansible.builtin.set_fact:
        build_start: '{{ lookup("pipe", "date +%s") }}'

    - name: Include customised variables
      ansible.builtin.include_vars: '{{ item }}'
      with_fileglob:
        - config.yml

    - name: Create temporary directory
      ansible.builtin.file:
        state: directory
        path: '/tmp/ansible'
        mode: '0775'

  post_tasks:
    - name: Print out end of build date and time and build duration
      ansible.builtin.debug:
        msg:
          - 'End of build: {{ lookup("pipe", "date +%Y-%m-%dT%H:%M:%S%z") }}'
          - 'Build duration: {{ lookup("pipe", "date +%s") | int - build_start | int }} s'

  roles:
    - handlers # This special 'role' defines all generic handlers.
    - rpisettings
    - apt
    - { role: firmware, when: moodlebox_update_firmware | bool }
    - hostname
    - useraccount
    - timezone
    - locales
    - wifi
    - zeroconf
    - rpiconnect
    - database
    - packages
    - packageconfig
    - partitionresize
    - webserver
    - moodleuninstall
    - moodledatabase
    - moodleinstall
    - cron
    - adminer
    - cert
    - rpiclone
    - branding
    - { role: sshkey, when: moodlebox_build_type == 'development' }
    - cleanup
