---

- name: Create directory for MathJax library
  ansible.builtin.file:
    path: '{{ moodlebox_moodle_source_dir }}/public/lib/mathjax'
    state: directory
    owner: 'www-data'
    group: '{{ moodlebox_username }}'
    mode: '0775'

- name: Download and unarchive MathJax library
  ansible.builtin.unarchive:
    src: 'https://github.com/mathjax/MathJax/archive/refs/tags/{{ moodlebox_mathjax_version }}.tar.gz'
    dest: '{{ moodlebox_moodle_source_dir }}/public/lib/mathjax'
    remote_src: true
    exclude:
      - 'es5/mml*.js'
      - 'es5/tex-chtml*.js'
      - 'es5/tex-mml-svg.js'
      - 'es5/tex-svg*.js'
      - '.github'
      - '.gitignore'
      - '.travis.yml'
      - '*.json'
      - '*.md'
      - 'LICENSE'
    extra_opts: [--strip-components=1]
    owner: 'www-data'
    group: '{{ moodlebox_username }}'
    mode: 'ug+w,o-w'

- name: Change MathJax library URL
  ansible.builtin.command:
    cmd: >
      {{ moodleinstall_config_cmd }}
      --component=filter_mathjaxloader
      --name=httpsurl
      --set=/lib/mathjax/es5/tex-mml-chtml.js
  register: moodleinstall_mathjax_url_result
  changed_when: 'moodleinstall_mathjax_url_result.rc == 0'
