---
- name: Set valid Moodle system paths
  ansible.builtin.command:
    cmd: >
      {{ moodleinstall_config_cmd }} --name={{ item.name }} --set={{ item.value }}
  with_items:
    - { name: 'pathtophp', value: '/usr/bin/php' }
    - { name: 'pathtodu', value: '/usr/bin/du' }
    - { name: 'pathtopython', value: '/usr/bin/python3' }
    - { name: 'pathtopdftoppm', value: '/usr/bin/pdftoppm' }
    - { name: 'pathtounoconv', value: '' }
    - { name: 'pathtosassc', value: '' }
    - { name: 'servicespage', value: '/user/contactsitesupport.php' }
  register: moodleinstall_system_paths_result
  changed_when: 'moodleinstall_system_paths_result.rc == 0'

- name: Disable Moodle debug messages display
  ansible.builtin.command:
    cmd: >
      {{ moodleinstall_config_cmd }} --name=debugdisplay --set=0
  register: moodleinstall_debugdisplay_result
  changed_when: 'moodleinstall_debugdisplay_result.rc == 0'
